---
abstract: 'class for inner representation ABNF-grammar.'
author:
  - 'Arseny Krasikov <nyaapa@cpan.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ABNF-Grammar
no_index:
  directory:
    - t
    - inc
requires:
  Parse::ABNF: 0.05
  Readonly: 1.03
  Storable: 2.39
  perl: 5.014
resources:
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/afiskon/pl-vkmp3
version: 0.01
